### ISSUE TITLE
M1 Native/Universal Binary

### ISSUE THREAD

**Issue by Babypopdip** [robrohan/WebArchiveExtractor#10]
Hi! Would it be possible to make an M1 native build?

**Comment by robrohan** [comment]
Hi Babypopdip,

I've just added a github action to auto build the project, and it seems to have worked. I'll take a look if I have time if we can just add the M1 to that build and then maybe publish from there. I am currently not on a Mac at the moment (I tend to move OSs quite a bit). I'll see what I can do.

In the meantime, if anyone want to pick this up, I am sure it's just a config change in xcode...

**Comment by IhorShevchuk** [comment]
Created pull request #11 to save universal binary on workflows page. However it can be stored there only for [90 days](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts):
> By default, GitHub stores build logs and artifacts for 90 days, and this retention period can be customized.

**Comment by unitof** [comment]
Couldn't they be published as Releases, which stay online indefinitely? (I'd love to take you up on a new build if possible.)

**Comment by robrohan** [comment]
I think I remember reading the auto publish as a release got removed - but that doesn't seem right. I'll have a look when I have some free time. I just kicked off another build so another version should appear soon.

**Comment by robrohan** [comment]
While not automatic on build, the latest release (on the release page) should now work on M1. I don't have an M1 to test on, so please re-open if that is not the case.

**Comment by unitof** [comment]
Works! Thanks so much.

For others’ convenience, link is https://github.com/robrohan/WebArchiveExtractor/releases/download/v1.1/WebArchiveExtractor.tar.zip.
