### ISSUE TITLE
Icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [robrohan/WebArchiveExtractor#14]
Hey @robrohan, 
You saved me a lot of hassle today. So, as a thank you, here's an app icon I've made.
It's based on Apple's Archive Utility app, with some rework. Feel free to use it if you like it 🤓
[PNG + ICNS files](https://github.com/robrohan/WebArchiveExtractor/files/11234453/WebArchiveExtractor.zip)

<img width="512" src="https://user-images.githubusercontent.com/101254295/232086183-39b27b6d-4caa-4b6d-8c3f-6b53498f142b.png">

**Comment by robrohan** [comment]
Thanks @Zabriskije I've updated the icon in the latest build - looks nice :)

**Comment by Zabriskije** [comment]
You're welcome :)
