### ISSUE TITLE
Binary download

### ISSUE THREAD

**Issue by fschwahn** [robrohan/WebArchiveExtractor#2]
I'm probably absolutely blind, but I just couldn't find a binary download, neither here nor on the project page. A hint would be appreciated :smiley:

**Comment by hkic** [comment]
[WebArchiveExtractor (WebArchive to HTML) download](https://github.com/robrohan/WebArchiveExtractor/downloads)

**Comment by robrohan** [comment]
Updated version: https://github.com/robrohan/WebArchiveExtractor/releases
