### ISSUE TITLE
EXC_BAD_ACCESS in Extractor.m loadSubArchives

### ISSUE THREAD

**Issue by necktwi** [robrohan/WebArchiveExtractor#4]
<img width="1280" alt="screen shot 2017-03-25 at 3 09 46 pm" src="https://cloud.githubusercontent.com/assets/2793912/24321258/fb80b994-116d-11e7-9d80-a37d4f84799b.png">

screenshot of the error

**Comment by robrohan** [comment]
I've just removed this code from the latest version.  I believe that code was to handle iframes which isn't really key to the point of the utility.  It'll be 'fixed' in the next release here in a minute...
